version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
    container_name: python_app
    restart: always
    command: >
      sh -c "python app/check_tpu.py && python app/app.py"
    network_mode: "host"
    privileged: true
    stdin_open: true
    tty: true
